In [25]:
import pandas as pd
import sqlite3

In [26]:
df = pd.read_csv('Valeurs_foncieÌ€res.csv')
df

C:\Users\utilisateur\AppData\Local\Temp\ipykernel_5040\3743481448.py:1: DtypeWarning: Columns (20,26,42,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Valeurs_foncieÌ€res.csv')

,Code service CH,Reference document,1 Articles CGI,2 Articles CGI,3 Articles CGI,4 Articles CGI,5 Articles CGI,No disposition,Date mutation,Nature mutation,...,Surface Carrez du 5eme lot,Nombre de lots,Code type local,Type local,Identifiant local,Surface reelle bati,Nombre pieces principales,Nature culture,Nature culture speciale,Surface terrain
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-02-03 00:00:00,Vente,...,NaN,1,2,Appartement,NaN,52,2,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-01-02 00:00:00,Vente,...,NaN,2,2,Appartement,NaN,48,3,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-01-08 00:00:00,Vente,...,NaN,2,2,Appartement,NaN,130,6,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-01-06 00:00:00,Vente,...,NaN,1,1,Maison,NaN,109,5,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-01-07 00:00:00,Vente,...,NaN,2,2,Appartement,NaN,91,4,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-06-30 00:00:00,Vente,...,NaN,1,2,Appartement,NaN,99,3,NaN,NaN,NaN
34165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-06-30 00:00:00,Vente,...,NaN,1,2,Appartement,NaN,56,3,NaN,NaN,NaN
34166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-06-25 00:00:00,Vente,...,NaN,2,2,Appartement,NaN,29,2,NaN,NaN,NaN
34167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-06-25 00:00:00,Vente,...,NaN,1,2,Appartement,NaN,48,3,NaN,NaN,NaN
34168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2020-06-11 00:00:00,Vente,...,NaN,1,2,Appartement,NaN,33,1,NaN,NaN,NaN

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34169 entries, 0 to 34168
Data columns (total 44 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Reference document          0 non-null      float64
 1   1 Articles CGI              0 non-null      float64
 2   2 Articles CGI              0 non-null      float64
 3   3 Articles CGI              0 non-null      float64
 4   4 Articles CGI              0 non-null      float64
 5   5 Articles CGI              0 non-null      float64
 6   No disposition              34169 non-null  int64
 7   Date mutation               34169 non-null  object
 8   Nature mutation             34169 non-null  object
 9   Valeur fonciere             34151 non-null  object
 10  No voie                     34036 non-null  float64
 11  B/T/Q                       2174 non-null   object
 12  Code type de voie           34169 non-null  int64
 13  Type de voie                33229 non-null  object
 14  Code voie                   34169 non-null  object
 15  Voie                        34169 non-null  object
 16  Code ID commune             34169 non-null  int64
 17  Code postal                 34168 non-null  float64
 18  Commune                     34169 non-null  object
 19  Code departement            34169 non-null  object
 20  Code commune                34169 non-null  int64
 21  Unnamed: 22                 1143 non-null   float64
 22  Section                     34168 non-null  object
 23  No plan                     34169 non-null  int64
 24  No Volume                   0 non-null      float64
 25  1er lot                     34169 non-null  object
 26  Surface Carrez du 1er lot   34169 non-null  object
 27  2eme lot                    0 non-null      float64
 28  Surface Carrez du 2eme lot  0 non-null      float64
 29  3eme lot                    0 non-null      float64
 30  Surface Carrez du 3eme lot  0 non-null      float64
 31  4eme lot                    0 non-null      float64
 32  Surface Carrez du 4eme lot  0 non-null      float64
 33  5eme lot                    0 non-null      float64
 34  Surface Carrez du 5eme lot  0 non-null      float64
 35  Nombre de lots              34169 non-null  int64
 36  Code type local             34169 non-null  int64
 37  Type local                  34169 non-null  object
 38  Identifiant local           0 non-null      float64
 39  Surface reelle bati         34169 non-null  int64
 40  Nombre pieces principales   34169 non-null  int64
 41  Nature culture              253 non-null    object
 42  Nature culture speciale     8 non-null      object
 43  Surface terrain             253 non-null    float64
dtypes: float64(20), int64(9), object(15)
memory usage: 11.5+ MB

In [39]:
mycolumns = ['Date mutation', 'Nature mutation', 'Nombre de lots', 'Code type local', 'Type local', 'Surface reelle bati', 'Nombre pieces principales', 'Valeur fonciere', 'No voie', 'B/T/Q']
df[mycolumns]

,Date mutation,Nature mutation,Nombre de lots,Code type local,Type local,Surface reelle bati,Nombre pieces principales,Valeur fonciere,No voie,B/T/Q
0,2020-02-03 00:00:00,Vente,1,2,Appartement,52,2,56000,190.0,A
1,2020-01-02 00:00:00,Vente,2,2,Appartement,48,3,165000,347.0,NaN
2,2020-01-08 00:00:00,Vente,2,2,Appartement,130,6,720000,58.0,NaN
3,2020-01-06 00:00:00,Vente,1,1,Maison,109,5,429250,140.0,NaN
4,2020-01-07 00:00:00,Vente,2,2,Appartement,91,4,220900,39.0,NaN
...,...,...,...,...,...,...,...,...,...,...
34164,2020-06-30 00:00:00,Vente,1,2,Appartement,99,3,1290000,4.0,NaN
34165,2020-06-30 00:00:00,Vente,1,2,Appartement,56,3,726000,38.0,NaN
34166,2020-06-25 00:00:00,Vente,2,2,Appartement,29,2,420000,13.0,NaN
34167,2020-06-25 00:00:00,Vente,1,2,Appartement,48,3,725000,16.0,NaN
34168,2020-06-11 00:00:00,Vente,1,2,Appartement,33,1,433000,3.0,NaN

In [28]:
communes = pd.read_excel('donnees_communes.xlsx')
communes

,REG,CODREG,COD,CODARR,CODCAN,CODCOM,COM,PMUN,PCAP,PTOT
0,Auvergne-RhÃƒÂ´ne-Alpes,11.0,91.0,1.0,08,100.0,Bouville,646.0,16.0,662.0
1,Auvergne-RhÃƒÂ´ne-Alpes,11.0,77.0,2.0,14.0,100.0,Le ChÃƒÂ¢telet-en-Brie,4339.0,67.0,4406.0
2,Auvergne-RhÃƒÂ´ne-Alpes,24.0,41.0,2.0,06,100.0,Les Hayes,170.0,8.0,178.0
3,Auvergne-RhÃƒÂ´ne-Alpes,24.0,36.0,3.0,08,100.0,Lourouer-Saint-Laurent,261.0,6.0,267.0
4,Auvergne-RhÃƒÂ´ne-Alpes,24.0,37.0,3.0,03,100.0,Ãƒâ€°peignÃƒÂ©-les-Bois,406.0,4.0,410.0
...,...,...,...,...,...,...,...,...,...,...
34986,Provence-Alpes-CÃƒÂ´te d'Azur,93.0,13.0,1.0,28.0,99.0,Saint-Paul-lÃƒÂ¨s-Durance,885.0,13.0,898.0
34987,Provence-Alpes-CÃƒÂ´te d'Azur,93.0,06,2.0,26.0,99.0,Puget-ThÃƒÂ©niers,1840.0,81.0,1921.0
34988,Provence-Alpes-CÃƒÂ´te d'Azur,93.0,84.0,1.0,08,99.0,Robion,4631.0,75.0,4706.0
34989,Provence-Alpes-CÃƒÂ´te d'Azur,93.0,83.0,1.0,11.0,99.0,Puget-sur-Argens,8062.0,108.0,8170.0
34990,Provence-Alpes-CÃƒÂ´te d'Azur,94.0,2A,1.0,11.0,99.0,Cozzano,276.0,0.0,276.0

In [40]:
mycolumns = ['REG', 'CODREG', 'COD', 'CODCOM', 'COM', 'PTOT']
communes[mycolumns]

,REG,CODREG,COD,CODCOM,COM,PTOT
0,Auvergne-RhÃƒÂ´ne-Alpes,11.0,91.0,100.0,Bouville,662.0
1,Auvergne-RhÃƒÂ´ne-Alpes,11.0,77.0,100.0,Le ChÃƒÂ¢telet-en-Brie,4406.0
2,Auvergne-RhÃƒÂ´ne-Alpes,24.0,41.0,100.0,Les Hayes,178.0
3,Auvergne-RhÃƒÂ´ne-Alpes,24.0,36.0,100.0,Lourouer-Saint-Laurent,267.0
4,Auvergne-RhÃƒÂ´ne-Alpes,24.0,37.0,100.0,Ãƒâ€°peignÃƒÂ©-les-Bois,410.0
...,...,...,...,...,...,...
34986,Provence-Alpes-CÃƒÂ´te d'Azur,93.0,13.0,99.0,Saint-Paul-lÃƒÂ¨s-Durance,898.0
34987,Provence-Alpes-CÃƒÂ´te d'Azur,93.0,06,99.0,Puget-ThÃƒÂ©niers,1921.0
34988,Provence-Alpes-CÃƒÂ´te d'Azur,93.0,84.0,99.0,Robion,4706.0
34989,Provence-Alpes-CÃƒÂ´te d'Azur,93.0,83.0,99.0,Puget-sur-Argens,8170.0
34990,Provence-Alpes-CÃƒÂ´te d'Azur,94.0,2A,99.0,Cozzano,276.0

In [29]:
geo = pd.read_excel('fr-esr-referentiel-geographique.xlsx')
geo

C:\Users\utilisateur\anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,regrgp_nom,reg_nom,reg_nom_old,aca_nom,dep_nom,com_code,com_code1,com_code2,com_id,com_nom_maj_court,...,fd_id,fr_id,fe_id,uu_id_99,au_code,au_id,auc_id,auc_nom,uu_id_10,geolocalisation
0,Province,Bourgogne-Franche-ComtÃƒÂ©,Franche-ComtÃƒÂ©,BesanÃƒÂ§on,Haute-SaÃƒÂ´ne,70088.0,70088.0,70088.0,C70088,BOURGUIGNON LES LA CHARITE,...,FD111,FR11,FE1,SO,NaN,AU997,C70088,Bourguignon-lÃƒÂ¨s-la-CharitÃƒÂ©,SO,"47.5075942378,5.96493598181"
1,Province,Bourgogne-Franche-ComtÃƒÂ©,Franche-ComtÃƒÂ©,BesanÃƒÂ§on,Haute-SaÃƒÂ´ne,70095.0,70095.0,70095.0,C70095,BREUREY LES FAVERNEY,...,FD111,FR11,FE1,SO,135.0,AU135,AU135,Vesoul,SO,"47.7448155296,6.14540506475"
2,Province,Bourgogne-Franche-ComtÃƒÂ©,Franche-ComtÃƒÂ©,BesanÃƒÂ§on,Haute-SaÃƒÂ´ne,70101.0,70101.0,70101.0,C70101,BROYE AUBIGNEY MONTSEUGNY,...,FD111,FR11,FE1,SO,25.0,AU025,AU025,Dijon,SO,"47.3305692734,5.5187191763"
3,Province,Bourgogne-Franche-ComtÃƒÂ©,Franche-ComtÃƒÂ©,BesanÃƒÂ§on,Haute-SaÃƒÂ´ne,70111.0,70111.0,70111.0,C70111,CALMOUTIER,...,FD111,FR11,FE1,SO,135.0,AU135,AU135,Vesoul,SO,"47.6443877301,6.28291281829"
4,Province,Bourgogne-Franche-ComtÃƒÂ©,Franche-ComtÃƒÂ©,BesanÃƒÂ§on,Haute-SaÃƒÂ´ne,70116.0,70116.0,70116.0,C70116,CHAGEY,...,FD111,FR11,FE1,SO,NaN,AU997,C70116,Chagey,SO,"47.6209267815,6.7351701305"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38911,Province,Auvergne-RhÃƒÂ´ne-Alpes,RhÃƒÂ´ne-Alpes,Grenoble,DrÃƒÂ´me,26137.0,26137.0,26137.0,C26137,FRANCILLON SUR ROUBION,...,FD111,FR11,FE1,SO,NaN,AU998,C26137,Francillon-sur-Roubion,SO,"44.6168821671,5.07198362932"
38912,Province,Auvergne-RhÃƒÂ´ne-Alpes,RhÃƒÂ´ne-Alpes,Grenoble,DrÃƒÂ´me,26138.0,26138.0,26138.0,C26138,LA GARDE ADHEMAR,...,FD111,FR11,FE1,SO,NaN,AU997,C26138,La Garde-AdhÃƒÂ©mar,SO,"44.3910321281,4.74995521601"
38913,Province,Auvergne-RhÃƒÂ´ne-Alpes,RhÃƒÂ´ne-Alpes,Grenoble,DrÃƒÂ´me,26142.0,26142.0,26142.0,C26142,GLANDAGE,...,FD111,FR11,FE1,SO,NaN,AU000,C26142,Glandage,SO,"44.6985798592,5.61337993572"
38914,Province,Auvergne-RhÃƒÂ´ne-Alpes,RhÃƒÂ´ne-Alpes,Grenoble,DrÃƒÂ´me,26147.0,26147.0,26147.0,C26147,GUMIANE,...,FD111,FR11,FE1,SO,NaN,AU000,C26147,Gumiane,SO,"44.5072339417,5.26749702819"
38915,Province,Auvergne-RhÃƒÂ´ne-Alpes,RhÃƒÂ´ne-Alpes,Grenoble,DrÃƒÂ´me,26149.0,26149.0,26149.0,C26149,HOSTUN,...,FD111,FR11,FE1,SO,118.0,AU118,AU118,Romans-sur-IsÃƒÂ¨re,SO,"45.0322321943,5.20271143898"

In [41]:
geo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38916 entries, 0 to 38915
Data columns (total 37 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   regrgp_nom         38916 non-null  object
 1   reg_nom            38916 non-null  object
 2   reg_nom_old        38916 non-null  object
 3   aca_nom            38916 non-null  object
 4   dep_nom            38916 non-null  object
 5   com_code           38916 non-null  object
 6   com_code1          38916 non-null  object
 7   com_code2          38916 non-null  object
 8   com_id             38916 non-null  object
 9   com_nom_maj_court  38916 non-null  object
 10  com_nom_maj        38916 non-null  object
 11  com_nom            38916 non-null  object
 12  uu_code            7625 non-null   object
 13  uu_id              38916 non-null  object
 14  uucr_id            38916 non-null  object
 15  uucr_nom           38916 non-null  object
 16  ze_id              38916 non-null  object
 17  dep_code           38916 non-null  object
 18  dep_id             38916 non-null  object
 19  dep_nom_num        38916 non-null  object
 20  dep_num_nom        38916 non-null  object
 21  aca_code           38916 non-null  float64
 22  aca_id             38916 non-null  object
 23  reg_code           38916 non-null  float64
 24  reg_id             38916 non-null  object
 25  reg_code_old       38916 non-null  float64
 26  reg_id_old         38916 non-null  object
 27  fd_id              38916 non-null  object
 28  fr_id              38916 non-null  object
 29  fe_id              38916 non-null  object
 30  uu_id_99           38916 non-null  object
 31  au_code            21444 non-null  object
 32  au_id              38916 non-null  object
 33  auc_id             38916 non-null  object
 34  auc_nom            38916 non-null  object
 35  uu_id_10           38916 non-null  object
 36  geolocalisation    36745 non-null  object
dtypes: float64(3), object(34)
memory usage: 11.0+ MB

In [46]:
mycolumns = ['regrgp_nom', 'reg_nom', 'reg_nom_old', 'reg_code', 'reg_id', 'reg_code_old', 'reg_id_old']
geo[mycolumns]

,regrgp_nom,reg_nom,reg_nom_old,reg_code,reg_id,reg_code_old,reg_id_old
0,Province,Bourgogne-Franche-ComtÃƒÂ©,Franche-ComtÃƒÂ©,27.0,R27,43.0,R43
1,Province,Bourgogne-Franche-ComtÃƒÂ©,Franche-ComtÃƒÂ©,27.0,R27,43.0,R43
2,Province,Bourgogne-Franche-ComtÃƒÂ©,Franche-ComtÃƒÂ©,27.0,R27,43.0,R43
3,Province,Bourgogne-Franche-ComtÃƒÂ©,Franche-ComtÃƒÂ©,27.0,R27,43.0,R43
4,Province,Bourgogne-Franche-ComtÃƒÂ©,Franche-ComtÃƒÂ©,27.0,R27,43.0,R43
...,...,...,...,...,...,...,...
38911,Province,Auvergne-RhÃƒÂ´ne-Alpes,RhÃƒÂ´ne-Alpes,84.0,R84,82.0,R82
38912,Province,Auvergne-RhÃƒÂ´ne-Alpes,RhÃƒÂ´ne-Alpes,84.0,R84,82.0,R82
38913,Province,Auvergne-RhÃƒÂ´ne-Alpes,RhÃƒÂ´ne-Alpes,84.0,R84,82.0,R82
38914,Province,Auvergne-RhÃƒÂ´ne-Alpes,RhÃƒÂ´ne-Alpes,84.0,R84,82.0,R82
38915,Province,Auvergne-RhÃƒÂ´ne-Alpes,RhÃƒÂ´ne-Alpes,84.0,R84,82.0,R82